### ISSUE TITLE
SSLContext unavailable on python versions lower than 2.7.9

### ISSUE THREAD

**Issue by 0x27** [pycepa/pycepa#23]
"AttributeError: 'module' object has no attribute 'SSLContext'"

After some research, it seems we won't be able to support Python versions below 2.7.9, unless we implement some kind of workaround for this issue. Debian 7, and some other distros, ship with 2.7.3 (or worse, 2.6...). I guess we will have to package a binary installer for these?

**Comment by entr0pist** [comment]
Closed by 3454753. SSLContext is there to remove insecure ciphers and set the TLS version. Older python version don't support TLS 1.2 anyway, so the work around here is to skip that setup and just open the default SSL object.

In the future we may want to look into another library that doesn't depend on newer versions of Python.
