### ISSUE TITLE
Remove 'tor' from project name.

### ISSUE THREAD

**Issue by entr0pist** [pycepa/pycepa#5]
https://www.torproject.org/docs/trademark-faq.html.en

The Tor project doesn't want people to use their name in other projects so we should respect that as soon as we think of an alternative.

**Comment by 0x27** [comment]
Apparently they prefer if we use "onion" or something. "pyonion" doesn't have a great ring to it, however, "onion" in latin is "cepa", and "pycepa" sounds fairly decentish as a proposal for renaming?
